<<<<<<< HEAD
version: '2.1'

jobs:
    test:
        docker:
            - image: cimg/node:24.0-browsers
        steps:
            - checkout
            - run: echo "Running example step, please edit this file"

workflows:
    main:
        jobs:
            - test
=======
version: "2.1"

jobs:
    test:
        docker:
            - image: cimg/node:24.0-browsers
        steps:
            - checkout
            - run: echo "Running example step, please edit this file"

workflows:
<<<<<<< HEAD
  main:
    jobs:
      - test
>>>>>>> 64b754cfe (fix(ci): populate cci-agent-setup.yml to fix "root is not an object" error)
=======
    main:
        jobs:
            - test
>>>>>>> 879e75bcf (style: apply automated autofixes (ruff / prettier / clang-format) [CodeQL Advanced])
