# https://circleci.com/docs/2.0/config-intro/

jobs:
    test:
        docker:
            - image: cimg/node:24.0-browsers
        steps:
            - checkout
            - run: echo "Running example step, please edit this file"
version: "2.1"
