-- Embeddings for chat messages to enable semantic memory retrieval
-- Uses VARBINARY(MAX) to store serialized float32 vector (little-endian)
-- If Azure SQL VECTOR type is available in target service version, this table
-- can be migrated to use VECTOR(<dim>) for native similarity operations.
